version: 1
disable_existing_loggers: False

formatters:
    full:
        format: "%(asctime)s | %(name)s | %(module)s::%(funcName)s::%(lineno)d | %(levelname)-8s | %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

    basic:
        format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: full
        stream: ext://sys.stdout

loggers:
    __main__:
        level: INFO

    audio:
        level: INFO

root:
    level: INFO
    handlers: [console]